filter:
    paths: ["src/*"]
    excluded_paths: ["vendor/*", "tests/*", "public/"]

tools:
    external_code_coverage: false

build:
    environment:
        php:
            version: 8.2
            ini:
                date.timezone: 'Europe/Madrid'
        hosts:
            aos_mysql: '127.0.0.1'
        mysql: false
        node: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false

    services:
        mi-servidor-mysql:
           image: mysql:8.0
           env:
               MYSQL_ROOT_PASSWORD: root
               MYSQL_DATABASE: db_name_test
           ports:
                - 3306
           ramdisks:
                - /var/lib/mysql

    nodes:
        analysis:
            tests:
               override:
                    - php-scrutinizer-run
                    - command: phpcs-run
                      use_website_config: true
    dependencies:
        before:
            - composer self-update
            - composer update --prefer-dist --no-progress
            - mv -f .env.scrutinizer .env
            - chmod 777 logs
        override:
            - true
    tests:
        before:
            -
               command: vendor/phpunit/phpunit/phpunit -c phpunit.xml.docker
               coverage:
                   file: 'logs/coverage.xml'
                   format: 'clover'
        override:
            - true

checks:
    php:
        code_rating: true
        duplication: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_parameter: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            abstract_class_name: ^Abstract|Factory$
            utility_class_name: 'Utils?$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: '^(?:is|has|should|may|supports)'
        more_specific_types_in_doc_comments: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_line_ending: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
    # javascript: false

coding_style:
    php: {  }
