version: "3"

services:
    web_server:
        build:
            context: .docker/apache
            dockerfile: Dockerfile
        container_name: aos_apache
        ports:
            - "8000:80"
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled:ro
            - .:/home/wwwroot/aos:rw
        depends_on:
            - backend

    database:
        image: mysql:5.7
        command: "--default-authentication-plugin=mysql_native_password --lower_case_table_names=2"
        container_name: aos_mysql
        ports:
            - "3306:3306"
        volumes:
            - .docker/data/db:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DATABASE_NAME:?"Variable MYSQL_DATABASE no definida"}
            # MYSQL_USER: ${DATABASE_USER:?"Variable MYSQL_USER no definida"}
            MYSQL_PASSWORD: ${DATABASE_PASSWD:?"Variable MYSQL_PASSWORD no definida"}
        restart: on-failure

    backend:
        build: .docker/php
        container_name: aos_php
        ports:
            - "9000:9000"
            # - "9003:9003"
        volumes:
            - .:/home/wwwroot/aos
        environment:
            MYSQL_TEST_DATABASE: ${DATABASE_TEST_NAME?"Variable MYSQL_TEST_DATABASE no definida"}
            DOCKER: 1
        depends_on:
            - database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: aos_phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        depends_on:
            - database
